version: '3.6'
services:
  pg_database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
volumes:
  pg_data: